/**
 * Maps each relic id to a game-icons.net icon from react-icons/gi.
 * Icons licensed under CC-BY 3.0 by Lorc, Delapouite and contributors
 * at game-icons.net. Attribution shown in Credits screen.
 */

import type { IconType } from "react-icons";
import {
  GiDualityMask,
  GiFallingOvoid,
  GiCrown,
  GiCrownedHeart,
  GiCheckeredFlag,
  GiLinkedRings,
  GiStrongMan,
  GiLightningTrio,
  GiBullseye,
  GiPerspectiveDiceSixFacesSix,
  GiBlackHoleBolas,
  GiConqueror,
  GiTriforce,
  GiOneEyed,
  GiStonePath,
  GiPentacle,
  GiGemini,
  GiSoundWaves,
  GiStoneBlock,
  GiChainMail,
  GiCrossedSwords,
  GiStraightPipe,
  GiTwoShadows,
  GiWolfHowl,
  GiMountainClimbing,
  GiThunderStruck,
  GiFeather,
  GiMusicalNotes,
  GiInfinity,
  GiMirrorMirror,
  GiCrystalShine,
  GiSnake,
  GiMountainRoad,
  GiTwoCoins,
  GiStarFormation,
  GiSandsOfTime,
  GiGrab,
  GiFunnel,
  GiRecycle,
  GiCompass,
  GiChessKnight,
  GiWaterfall,
  GiBrokenShield,
  GiNightSky,
  GiPointing,
  GiFallingStar,
  GiQueenCrown,
  GiPentagramRose,
  GiOpenBook,
  GiCrystalBall,
  GiSamuraiHelmet,
  GiAbstract024,
  GiHarp,
  GiPawPrint,
  GiAncientColumns,
  GiBrokenAxe,
  GiKnightBanner,
  GiBloodySword,
  GiHourglass,
  GiBleedingEye,
  GiInfinity as GiInfinityAlt,
} from "react-icons/gi";

/** relic id -> GameIcons component */
export const RELIC_ICON_MAP: Record<string, IconType> = {
  eco_par: GiDualityMask,
  pulso_bajo: GiFallingOvoid,
  corona_alta: GiCrown,
  doble_corona: GiCrownedHeart,
  final_pesado: GiCheckeredFlag,
  cadena_tensa: GiLinkedRings,
  mano_firme: GiStrongMan,
  impulso_inicial: GiLightningTrio,
  precision: GiBullseye,
  seis_dorado: GiPerspectiveDiceSixFacesSix,
  cero_vacio: GiBlackHoleBolas,
  dominio_total: GiConqueror,
  tres_magico: GiTriforce,
  uno_solitario: GiOneEyed,
  cuatro_estable: GiStonePath,
  cinco_central: GiPentacle,
  dos_gemelos: GiGemini,
  amplificador: GiSoundWaves,
  base_solida: GiStoneBlock,
  cadena_maestra: GiChainMail,
  doble_filo: GiCrossedSwords,
  simple_efectivo: GiStraightPipe,
  doble_amenaza: GiTwoShadows,
  impar_salvaje: GiWolfHowl,
  escalador: GiMountainClimbing,
  parejas_perfectas: GiLinkedRings,
  racha_imparable: GiThunderStruck,
  minimalista: GiFeather,
  ritmo_perfecto: GiMusicalNotes,
  maestro_cadenas: GiInfinity,
  reflejo: GiMirrorMirror,
  pureza_doble: GiCrystalShine,
  serpiente: GiSnake,
  avalancha_total: GiMountainRoad,
  fortuna: GiTwoCoins,
  supernova: GiStarFormation,
  reloj_arena: GiSandsOfTime,
  mano_larga: GiGrab,
  filtro: GiFunnel,
  reciclador: GiRecycle,
  explorador: GiCompass,
  tactico: GiChessKnight,
  // ---- S6 / S7 relics ----
  cascada_patrones: GiWaterfall,
  corona_rota: GiBrokenShield,
  sello_firmamento: GiNightSky,
  dedo_luminoso: GiPointing,
  caida_prolongada: GiFallingStar,
  coronacion: GiQueenCrown,
  hexagrama_sagrado: GiPentagramRose,
  lector_formas: GiOpenBook,
  oraculo_cosmico: GiCrystalBall,
  disciplina: GiSamuraiHelmet,
  tres_lineas: GiTriforce,
  eco_roto: GiAbstract024,
  armonia_divina: GiHarp,
  // ---- S8 relics ----
  pisada_lobo: GiPawPrint,
  linaje_estable: GiAncientColumns,
  filo_roto: GiBrokenAxe,
  estandarte_andante: GiKnightBanner,
  sangre_pactada: GiBloodySword,
  reloj_quebrado: GiHourglass,
  mirada_vacio: GiBleedingEye,
  eternidad: GiInfinityAlt,
};

export function getRelicIcon(relicId: string): IconType | null {
  return RELIC_ICON_MAP[relicId] ?? null;
}
