/**
 * Maps each relic id to a game-icons.net icon from react-icons/gi.
 * Icons licensed under CC-BY 3.0 by Lorc, Delapouite and contributors
 * at game-icons.net. Attribution shown in Credits screen.
 */

import type { IconType } from "react-icons";
import {
  GiDualityMask,
  GiFallingOvoid,
  GiCrown,
  GiCrownedHeart,
  GiCheckeredFlag,
  GiLinkedRings,
  GiStrongMan,
  GiLightningTrio,
  GiBullseye,
  GiPerspectiveDiceSixFacesSix,
  GiBlackHoleBolas,
  GiConqueror,
  GiTriforce,
  GiOneEyed,
  GiStonePath,
  GiPentacle,
  GiGemini,
  GiSoundWaves,
  GiStoneBlock,
  GiChainMail,
  GiCrossedSwords,
  GiStraightPipe,
  GiTwoShadows,
  GiWolfHowl,
  GiMountainClimbing,
  GiThunderStruck,
  GiFeather,
  GiMusicalNotes,
  GiInfinity,
  GiMirrorMirror,
  GiCrystalShine,
  GiSnake,
  GiMountainRoad,
  GiTwoCoins,
  GiStarFormation,
  GiSandsOfTime,
  GiGrab,
  GiFunnel,
  GiRecycle,
  GiCompass,
  GiChessKnight,
} from "react-icons/gi";

/** relic id -> GameIcons component */
export const RELIC_ICON_MAP: Record<string, IconType> = {
  eco_par: GiDualityMask,
  pulso_bajo: GiFallingOvoid,
  corona_alta: GiCrown,
  doble_corona: GiCrownedHeart,
  final_pesado: GiCheckeredFlag,
  cadena_tensa: GiLinkedRings,
  mano_firme: GiStrongMan,
  impulso_inicial: GiLightningTrio,
  precision: GiBullseye,
  seis_dorado: GiPerspectiveDiceSixFacesSix,
  cero_vacio: GiBlackHoleBolas,
  dominio_total: GiConqueror,
  tres_magico: GiTriforce,
  uno_solitario: GiOneEyed,
  cuatro_estable: GiStonePath,
  cinco_central: GiPentacle,
  dos_gemelos: GiGemini,
  amplificador: GiSoundWaves,
  base_solida: GiStoneBlock,
  cadena_maestra: GiChainMail,
  doble_filo: GiCrossedSwords,
  simple_efectivo: GiStraightPipe,
  doble_amenaza: GiTwoShadows,
  impar_salvaje: GiWolfHowl,
  escalador: GiMountainClimbing,
  parejas_perfectas: GiLinkedRings,
  racha_imparable: GiThunderStruck,
  minimalista: GiFeather,
  ritmo_perfecto: GiMusicalNotes,
  maestro_cadenas: GiInfinity,
  reflejo: GiMirrorMirror,
  pureza_doble: GiCrystalShine,
  serpiente: GiSnake,
  avalancha_total: GiMountainRoad,
  fortuna: GiTwoCoins,
  supernova: GiStarFormation,
  reloj_arena: GiSandsOfTime,
  mano_larga: GiGrab,
  filtro: GiFunnel,
  reciclador: GiRecycle,
  explorador: GiCompass,
  tactico: GiChessKnight,
};

export function getRelicIcon(relicId: string): IconType | null {
  return RELIC_ICON_MAP[relicId] ?? null;
}
